### PR TITLE
feat(history-browser) add browser history page state setter and getter

### PR DESCRIPTION
**Pull request by jwx**
Set and get a key's value for the current page in the browser history.

Depending on new module aurelia-storage (currently in jwx/storage).
Necessary for PR aurelia/router/navigation-flags (aurelia/router#436).

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@jwx Would you remove all dist files from this PR please?

**Comment by jwx** [comment]
@EisenbergEffect Done. Sorry for the inconvenience.

**Comment by EisenbergEffect** [comment]
The more I think about this, I feel less comfortable with adding aurelia-storage. @jwx Would you be willing to define the Storage inside this History module, but with only the most basics, implementation that uses an in-memory data store? Then, we could have a more advanced implementation as a separate module. I'm just uncomfortable complicating things to much and adding another required dependency into the chain.

**Comment by jwx** [comment]
I fully understand about adding another dependency. Not sure what you mean with in-memory data store, though. I could extract the necessary code from my Storage and add it to history-browser directly, if that works for you? @EisenbergEffect

**Comment by jwx** [comment]
I could also add a flag to deactivate the use of the history state (and in effect, the flags) to avoid conflicts if necessary. @EisenbergEffect

**Comment by EisenbergEffect** [comment]
How large was the code. Can you provide me with a quick link to that?

**Comment by jwx** [comment]
@EisenbergEffect It's just a few lines, so I've added a new commit that doesn't have the depency on Storage. The flag to deactivate page tracking should really be in the router module. Let me know if you want me to add it.

**Comment by EisenbergEffect** [comment]
@jwx I finally got this merged. Sorry for taking so long to consider this. Would you be interested in sending a PR to the history module to stub out these two methods as part of the history interface?

**Comment by jwx** [comment]
@EisenbergEffect No worries. And sure, I'll put together the PR.

**Pull request merged**
