### PR TITLE
Allow force reloading, code cleanup

### PR DESCRIPTION
**Pull request by bryanrsmith**

### CODE REVIEW

**Comment by alvarezmario** [comment]
Could you squash your commits and check if you've signed our CLA. :joy:

**Comment by EisenbergEffect** [comment]
@bryanrsmith I trust you here. If you think it's good to go, please merge it in. I have the first version of the platfrom abstraction layer ready and would like to incorporate it into the history library today or tomorrow, but don't want to conflict with your work here. So, let me know when this is in.

**Comment by bryanrsmith** [comment]
@EisenbergEffect Added one more commit to move `handleLinkClick` from router to this repo. It should be merged with aurelia/router#221. Both PRs should be good to go if you're happy with the changes.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Great. I will review all shortly and do the merge. Thanks for the awesome effort!

**Pull request merged**
