### PR TITLE
router.reset() url redirect

### PR DESCRIPTION
**Pull request by ochart2**
I have an issue where after authentication the router is reset and reconfigured. 
I then want to route to a new empty route, but the code exits at this point and the url is never loaded.
If there is a better way of doing this?  If so, please let me know.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
So, you are already at the empty route, and you want to re-navigate to it because the configuration for the empty route has changes, but nothing happens. Is that correct?

**Comment by ochart2** [comment]
Hi Rob, yes that's exactly it.

**Comment by EisenbergEffect** [comment]
@ochart2 I don't think I this PR is the best way to solve the problem. That would have some other side-effects. However, I do want to solve your issue. I'm going to leave this PR open until I implement a better solution. Hang in there!

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you take a look at this? I don't think we want to make the change in this PR, but we need to see if there's a way we can solve the problem.

**Comment by bryanrsmith** [comment]
Maybe we can perform a navigation, but bypass history & just invoke the router's handler (loadUrl) using the current fragment + query? Probably with slightly different handling to make sure we use the correct previous instruction, etc..

We could also try to make the route config more flexible so that a reconfiguration wouldn't be necessary. Eg, accept a function in place of moduleId that could dynamically choose a module.

**Comment by EisenbergEffect** [comment]
@bryanrsmith There's a property called moduleStrategy you can set on the route config that is a function which can dynamically choose a module id. If you get a chance, check it out. Maybe it will work for this?

**Comment by ochart2** [comment]
Hey guys, just wanted to say I'm not experiencing this issue anymore.
Thanks!

**Comment by EisenbergEffect** [comment]
Awesome!

**Comment by ochart2** [comment]
Guys, I just pulled the latest.. It's still not navigating :( Sorry...
I log in on a blank path, reset the router, and then navigate blank again to point to my newly authenticated route at which point it does not navigate.

Once again sorry, I know you guys are busy.  If there is anything I can do, like change the way I call the router, to reload a route, just let me know.

Thanks for effort, you guys are doing a great job! Loving the framework!

**Comment by EisenbergEffect** [comment]
@bryanrsmith Maybe we can an additional parameter to the navigate method `force:true` or something like that to enable the router to run even when the route is the same. Any thoughts on this?

**Comment by ochart2** [comment]
That would work for me :)

**Comment by bryanrsmith** [comment]
Sounds good to me. We could also set a flag in the reset method that lets us bypass the location check, but I think the parameter would be more useful.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you open a new issue on the router, that describes the problem and the new solution. After that, let me know and I'll close out this PR. Thanks!

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can I close this PR? Do we have an issue tracking the proposed solution?

**Comment by bryanrsmith** [comment]
Yep. aurelia/router#201

**Pull request closed without merging**
